//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.ErrorsMessage", typeof(ErrorsMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        public static string MSG_ERROR_LOGIN {
            get {
                return ResourceManager.GetString("MSG_ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again !.
        /// </summary>
        public static string MSG_ERROR_PASS_WORD {
            get {
                return ResourceManager.GetString("MSG_ERROR_PASS_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại..
        /// </summary>
        public static string MSG_EXIST {
            get {
                return ResourceManager.GetString("MSG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed.
        /// </summary>
        public static string MSG_FAILED {
            get {
                return ResourceManager.GetString("MSG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có tối đa {1} ký tự..
        /// </summary>
        public static string MSG_MAX_LENGTH {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại..
        /// </summary>
        public static string MSG_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ..
        /// </summary>
        public static string MSG_NOT_VALIDATE {
            get {
                return ResourceManager.GetString("MSG_NOT_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được bỏ trống..
        /// </summary>
        public static string MSG_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error.
        /// </summary>
        public static string MSG_SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("MSG_SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account has been locked out..
        /// </summary>
        public static string MSG_VALID_BLOCK_AUTH {
            get {
                return ResourceManager.GetString("MSG_VALID_BLOCK_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is the same as the old password..
        /// </summary>
        public static string MSG_VALID_PASS_WORD_NEW {
            get {
                return ResourceManager.GetString("MSG_VALID_PASS_WORD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã là cấp trên. Vui lòng xóa tất cả thuộc tính cấp dưới!.
        /// </summary>
        public static string MSG_VALID_REMOVE_PARENT {
            get {
                return ResourceManager.GetString("MSG_VALID_REMOVE_PARENT", resourceCulture);
            }
        }
    }
}
